### ISSUE TITLE
Minor Typo 9.2.1

### ISSUE THREAD

**Issue by BergProfJ** [bnmnetp/httlads#12]
Minor typo in first sentence of section 9.2.1 (Query Language):

Whatever the database might, there needs to be a way to extract data from it and a lot of these systems have agreed on a shared language for accessing data. 

Should probably be

Whatever the database might **be**, there needs to be a way to extract data from it and a lot of these systems have agreed on a shared language for accessing data.

**Comment by bnmnetp** [comment]
fixed.
