### ISSUE TITLE
System Message: ERROR/3 - Unknown directive type "jupyter-execute"

### ISSUE THREAD

**Issue by OttoBorchert** [bnmnetp/httlads#14]
There is a system error occurring in the live version of textbook currently on Runestone, showing up in sections 5.2, 5.4, 9.8, 9.11, and 9.12.

"System Message: ERROR/3 (/home/bmiller/Runestone/web2py/applications/runestone/books/httlads/_sources/MovieData/pandas_kungfu.rst, line 20)"

Unknown directive type “jupyter-execute”.

The file path changes in each of the sections. I've attached an example image of the error as well.

![HTTLADS_SystemError](https://user-images.githubusercontent.com/15854087/83207747-97b99e00-a119-11ea-89ea-8a9509b8dbad.PNG)

Pretty sure I can just have my students use the code inside the error message when my summer class starts next week, but still wanted to let you know.

Thanks!

**Comment by bnmnetp** [comment]
Sorry about that, I remember seeing the error message on the last build, and updating the plugin.  But apparently I did not deploy a new build.

Should be good now.  I’m not seeing the errors in the book anymore.

**Comment by OttoBorchert** [comment]
Looks great. Thanks for the quick response!

**Comment by bnmnetp** [comment]
Happy to hear that.  Good luck with the course and let me know how it goes, and if you have suggestions.
