### ISSUE TITLE
SQL Autograder produces no output and runtime error when assert is out of bounds

### ISSUE THREAD

**Issue by OttoBorchert** [bnmnetp/httlads#21]
To reproduce:

Go to section 9.4, Activity 3 (sql_bikeshare_filter_ex1) and use the following SQL query:

SELECT * FROM trip_data WHERE bike_number == 'W01274' AND duration < 900 LIMIT 10

(Note: I included LIMIT 10 because all of the examples in this section did).

Click 'Save & Run'

There is no output in the webpage, but the following is in the Chrome Console. 

activecode_sql.js:188 Uncaught TypeError: Cannot read property '0' of undefined
    at SQLActiveCode.testOneAssert (activecode_sql.js:188)
    at SQLActiveCode.autograde (activecode_sql.js:165)
    at SQLActiveCode.runProg (activecode_sql.js:143)
    at HTMLButtonElement.dispatch (jquery.js:2)
    at HTMLButtonElement.v.handle (jquery.js:2)

Digging around a bit, it's because I included the LIMIT 10 clause (It works fine when I remove it). There should be a range check on the assert statements to ensure they are not out of bounds, with a message to the student saying they don't have enough output.

**Comment by bnmnetp** [comment]
You are 100% right.  I just noticed this myself while looking at your PR.

**Comment by bnmnetp** [comment]
fixed it.
