### ISSUE TITLE
Outdated link in section 5.2.1

### ISSUE THREAD

**Issue by wjwoker** [bnmnetp/httlads#7]
The data in section 5.2.1 should be able to be obtained from the Kaggle link, however, the link leads to a 404 page. This should be fixed so that it links to [https://www.kaggle.com/rounakbanik/the-movies-dataset](https://www.kaggle.com/rounakbanik/the-movies-dataset), which is an updated URL for the same dataset.

**Comment by bnmnetp** [comment]
Thanks, updated.
